main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

create_record:
    path:     /create
    defaults: { _controller: MainBundle:Default:create }

move_record:
    path:    /move
    defaults: { _controller: MainBundle:Default:move }

create_and_move_record:
    path:    /createAndMove
    defaults: { _controller: MainBundle:Default:createAndMove }